import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


import * as fcl from "@onflow/fcl";
import "../flow/config";
import { useEffect, useState } from 'react';
import Navbar from '../components/Navbar';
export default function Home() {

  const [user, setUser] = useState<any>({ loggedIn: null });

  useEffect(() => {
    fcl.currentUser.subscribe(setUser);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gradient-to-b from-[#114357] to-[#f29492]  '>
        <Navbar />
        <div className=" h-[100vh] w-[100vw] flex ">
          <div className='h-full flex justify-around w-full '>

            <div className='h-full flex flex-1  justify-center items-center'>DEX1</div>
            <div className='h-full flex jusify-center flex-1 justify-center items-center '>DEX2</div>
            <div className='h-full flex justify-center items-center flex-1 '>DEX3</div>
          </div>

        </div>

      </main>
    </>
  )
}
